#include "CBasePlayerItem_vfunc.h"
int __thiscall (*CBasePlayerWeapon::pf131)(CBasePlayerWeapon* this, ...);
void __thiscall (*CBasePlayerWeapon::ExtractAmmo)(CBasePlayerWeapon* this, CBasePlayerWeapon*);
void __thiscall (*CBasePlayerWeapon::ExtractClipAmmo)(CBasePlayerWeapon* this, CBasePlayerWeapon*);
int __thiscall (*CBasePlayerWeapon::pf134)(CBasePlayerWeapon* this, ...);
void __thiscall (*CBasePlayerWeapon::AddWeapon)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::PlayEmptySound)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::ResetEmptySound)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::SendWeaponAnim)(CBasePlayerWeapon* this, int, int);
void __thiscall (*CBasePlayerWeapon::IsUseable)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::PrimaryAttack)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::SecondaryAttack)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::Reload)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::WeaponIdle)(CBasePlayerWeapon* this);
void __thiscall (*CBasePlayerWeapon::RetireWeapon)(CBasePlayerWeapon* this);
BOOL __thiscall (*CBasePlayerWeapon::ShouldWeaponIdle)(CBasePlayerWeapon* this);
BOOL __thiscall (*CBasePlayerWeapon::pf146)(CBasePlayerWeapon* this);
BOOL __thiscall (*CBasePlayerWeapon::UseDecrement)(CBasePlayerWeapon* this);
int __thiscall (*CBasePlayerWeapon::pf148[5])(CBasePlayerWeapon* this, ...);
int __thiscall (*CBasePlayerWeapon::GetMaxClip)(CBasePlayerWeapon* this);
int __thiscall (*CBasePlayerWeapon::pf154[5])(CBasePlayerWeapon* this, ...);